---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create report-server directory
  sudo: True
  file:
    path: "{{ reports_server_root_path }}"
    recurse: yes
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Create report-server archive directory
  sudo: True
  file:
    path: "{{reports_server_root_path}}/{{ reports_server_index_path }}"
    recurse: yes
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Disable the default site
  sudo: True
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Set the nginx config file
  sudo: True
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/rally-reports.conf
  notify: restart nginx

- name: Enable the nginx config file
  sudo: True
  file:
    src: /etc/nginx/sites-available/rally-reports.conf
    dest: /etc/nginx/sites-enabled/rally-reports.conf
    state: link
  notify: restart nginx

- name: Copy example report
  sudo: True
  copy:
    src: rally-example-report.html
    dest: "{{ reports_server_root_path }}/index.html"
    force: no
    owner: www-data
    group: www-data
