---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Git repository vars
perfkitbenchmarker_git_repo: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker.git
perfkitbenchmarker_git_install_branch: 34daa1c6134a33534e2521271e2202f2a6529b96
perfkitbenchmarker_git_dest: "/opt/perkitbenchmarker_{{ perfkitbenchmarker_git_install_branch | replace('/', '_') }}"

# PIP vars
## Path to pip download/installation script.
pip_upstream_repo_url: https://bootstrap.pypa.io
pip_get_pip_url: "{{ pip_upstream_repo_url }}/get-pip.py"

# Additional options that you might want to pass to "get-pip.py" when installing pip.
# Default `pip_get_pip_options` is an empty string.
pip_get_pip_options: ""

perfkitbenchmarker_apt_packages:
  - build-essential
  - python-dev

perfkitbenchmarker_requires_pip_packages:
  - python-novaclient
  - virtualenv

perfkitbenchmarker_pip_packages:
  - "file://{{ perfkitbenchmarker_git_dest }}"
